### ISSUE TITLE
CodeTime Token無法獲取

### ISSUE THREAD

**Issue by fkcailiniyazi** [datreks/codetime-web#130]
![Screenshot 2021-06-22 110130](https://user-images.githubusercontent.com/54360982/122896278-35959180-d349-11eb-80bf-b7e93b4358da.png)
你好，
我點擊了刷新token之後vs code上無法使用CodeTime了，然後試圖從web上獲取新的token，複製功能好像失效了，麻煩看一下。

**Comment by si9ma** [comment]
@fkcailiniyazi already fixed! You check again!

**Comment by fkcailiniyazi** [comment]
Many thanks,
