### ISSUE TITLE
Cannot create new token with Refresh Token button.

### ISSUE THREAD

**Issue by ttpro1995** [datreks/codetime-web#137]
The page: https://codetime.datreks.com/account
Picture ![p](https://i.imgur.com/pRLyKw1.png)

There is no token. When I click Refresh Token, nothing happen. 

Open developer tool and check Network, I see: 

GET https://codetime-api.datreks.com/updateToken

Response: 
```
{"code":-1,"message":"invalid token/token expired"}
```

**Comment by awesomelewis2007** [comment]
![image](https://user-images.githubusercontent.com/60709927/124351545-ef66ea80-dbf2-11eb-96a4-660c34d3fbb2.png)

**Comment by MrMasrozYTLIVE** [comment]
How did you even registered?

**Comment by si9ma** [comment]
@awesomelewis2007 @ttpro1995 @MrMasrozYTLIVE fixed! Sorry, I have been too busy recently. The problem is caused by too much data. We will expand the storage space in the future.
