### ISSUE TITLE
后端无法正常返回用户信息，并无限要求登录

### ISSUE THREAD

**Issue by WOSHIZHAZHA120** [datreks/codetime-web#185]
今天换了个设备, 发现无法登录了

习惯性的按下 F12 查看请求发现后台返回 ```500``` 以及错误码 ```-1```
以下是错误信息

```Error 1290: The MySQL server is running with the LOCK_WRITE_GROWTH option so it cannot execute this statement```

如果是阿里云的话可能是数据库满了

![图片](https://user-images.githubusercontent.com/52521836/145679041-69ec39db-f128-4aae-ac5b-13f882118c90.png)
![图片](https://user-images.githubusercontent.com/52521836/145679045-2db55eba-3d1d-4265-a7b9-803630ffda86.png)

**Comment by si9ma** [comment]
@WOSHIZHAZHA120 mysql storage space is full and has been repaired
