### ISSUE TITLE
data not submit ?

### ISSUE THREAD

**Issue by ttpro1995** [datreks/codetime-web#193]
I install codetime plugin, and enter token on both VS Code and pycharm. I use for few hours of coding. 

So far, I see nothing on https://codetime.datreks.com/project

The token I am using: 
```
c88e9a04-959e-4a95-81b9-842cc7074373
```

**Comment by billmdevs** [comment]
@si9ma @Jannchie Same issue after a couple of months. Has someone looked at it?

**Comment by jacrys** [comment]
https://codetime-api.datreks.com/  seems to be down. Do you know if this is even maintained anymore?  @si9ma @Jannchie?

**Comment by si9ma** [comment]
@jacrys It has been fixed. We plan to conduct a round of refactoring after the Chinese New Year to better ensure service stability.
