### ISSUE TITLE
Error in login

### ISSUE THREAD

**Issue by kaname-png** [datreks/codetime-web#204]
![image](https://user-images.githubusercontent.com/56084970/160248059-05c25428-3fcd-4503-bf3d-82a9bc0fd256.png)

**Comment by si9ma** [comment]
@kaname-png fixed!

**Comment by kaname-png** [comment]
@si9ma thanks
Also, I think the api is broken because the top 10 programmers never loads and I see that the data is never uploaded to the platform as I spent 1 hour today and the timer never went past 0 and on the website it says there is no data recorded
