### ISSUE TITLE
Option to export Data

### ISSUE THREAD

**Issue by flawnn** [datreks/codetime-web#258]
Hey,

do you have an option to export data? You should implement this, as soon as possible if not done already, to stay GDPR-compliant and it'd be generally also great to have it for portability reasons.

Cheers

**Comment by Jannchie** [comment]
Thank you for your feedback. It's in our plan. We will implement this feature as soon as possible. I think it will happen within this month.

**Comment by Jannchie** [comment]
It's later than planned, but we've finally implement the option to export data. I hope you understand our situation.
