### ISSUE TITLE
Error displaying Dashboard.

### ISSUE THREAD

**Issue by AstragoDE** [datreks/codetime-web#266]
After logging in to CodeTime on `codetime.dev` with GitHub, I am seeing the following error in the route `/dashboard`.
![image](https://user-images.githubusercontent.com/51675359/234843489-021ca782-5ba0-4ae6-95c9-69c9e8b3546e.png)

The bug only appears after data was uploaded to CodeTime via the extension (tested using the VS Code extension).

**Comment by Jannchie** [comment]
Thanks for the feedback, we are fixing it.

**Comment by Jannchie** [comment]
We think we have fixed the issue, if the problem persists, please reopen the issue.
