### ISSUE TITLE
Unable to Login via Github on website

### ISSUE THREAD

**Issue by seanblonien** [datreks/codetime-web#78]
I get this error when clicking "Login with Github" button.

![image](https://user-images.githubusercontent.com/33133478/108927219-b8554c80-75f4-11eb-9a82-15cbc495b9e5.png)

The Github part seems to work, but the callback seems to break with that error. I have no idea what it means.

Tested in Chrome Incognito browser.

**Comment by si9ma** [comment]
@seanblonien Fixed! You can try again!

**Comment by seanblonien** [comment]
Awesome, it works now, thanks!

**Comment by MasterBrian99** [comment]
same error  again.
![](https://i.imgur.com/msLqFKb.png)

any alternative way to fix this error ?

**Comment by MasterBrian99** [comment]
it's working now  🥳

**Comment by tommytim0515** [comment]
Sorry but this error is happening again...
![image](https://user-images.githubusercontent.com/44408451/164977889-f07bf8b5-5c48-46d1-b736-d0560a60c413.png)

**Comment by si9ma** [comment]
@tommytim0515 fixed!
